/**
 * typen-kopf.mjs — setzt den Hinweis über die erzeugte Typdatei.
 *
 * Läuft direkt nach openapi-typescript (siehe npm-Skript `typen`). Ohne diesen
 * Schritt wäre der Hinweis nach dem ersten Neuerzeugen wieder weg — und ein
 * Hinweis, der sich selbst löscht, ist keiner.
 */

import { readFile, writeFile } from 'node:fs/promises';

const ZIEL = new URL('../src/lib/api-typen.ts', import.meta.url);

const KOPF = `/**
 * api-typen.ts — ERZEUGT. Nicht von Hand bearbeiten.
 *
 * Quelle ist das OpenAPI-Schema des Servers, also src/neu/modelle.py.
 * Neu erzeugen, mit laufendem Server (uvicorn src.neu.server:app --port 8002):
 *
 *     npm run typen
 *
 * Die Datei wird committet, damit ein Build ohne laufenden Server durchläuft.
 * Wer hier von Hand ändert, verliert es beim nächsten Lauf — und schlimmer:
 * die Typen behaupten dann etwas, das der Server nicht liefert. Gewollt ist
 * das Gegenteil: benennt jemand ein Feld in modelle.py um, soll der Build
 * scheitern und die Stelle nennen.
 */

`;

const ERZEUGER_KOPF = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

const inhalt = await readFile(ZIEL, 'utf8');
const rumpf = inhalt.startsWith(ERZEUGER_KOPF)
	? inhalt.slice(ERZEUGER_KOPF.length)
	: inhalt.startsWith(KOPF)
		? inhalt.slice(KOPF.length)
		: inhalt;

await writeFile(ZIEL, KOPF + rumpf, 'utf8');
console.log('Kopfhinweis gesetzt → src/lib/api-typen.ts');
